Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7-i386"
  config.vm.synced_folder "../../", "/photish"
  config.vm.provision "shell", path: "test-install.sh", privileged: false
end
