module TaskConfig
  EXPECTED_RUBY_VERSION = '2.2.2'
  TRAVELING_RUBY_VERSION = "20150715-#{EXPECTED_RUBY_VERSION}"

  PACKAGING_DIR = 'packaging'
  WORKING_DIR = ENV['WORKING_DIR']
  BINARY_DIR = ENV['BINARY_DIR'] || 'pkg'
  CACHE_DIR = ENV['CACHE_DIR'] || 'tmp/packaging'
  RELEASES_DIR = "#{CACHE_DIR}/releases"
  SCRATCH_DIR = "#{CACHE_DIR}/scratch"
end
